services:
  azfetchbro:
    image: azfetchbro:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TB_ADX_RESOURCE=${TB_ADX_RESOURCE:-https://api.kusto.windows.net}
      - TB_EXPIRY_SKEW_MS=${TB_EXPIRY_SKEW_MS:-120000}
      - TB_DEFAULT_SAS_TTL_MS=${TB_DEFAULT_SAS_TTL_MS:-86400000}
      - TB_POLICY_FILE=/etc/azfetchbro/policy.json
      - TB_TOKENS_FILE=/etc/azfetchbro/tokens.json
    volumes:
      - ./azfetchbro-service/policy.json:/etc/azfetchbro/policy.json:ro
      - ./azfetchbro-service/tokens.json:/etc/azfetchbro/tokens.json:ro
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:8080/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
    logging:
      driver: "local"
      options:
        max-size: "500m"
        max-file: "6"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - azfetchbro
    ports:
      - "127.0.0.1:${NGINX_PORT:-8443}:8443"
    volumes:
      # Main nginx config file (provided by user)
      - ./nginx-service/nginx.conf:/etc/nginx/nginx.conf:ro
      # Directory with TLS materials (provided by user, same folder), mounted for reference in config
      - ./nginx-service/certs:/etc/nginx/external:ro
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --no-check-certificate --tries=1 --spider https://127.0.0.1:8443/nginx-health || exit 1"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
    logging:
      driver: "local"
      options:
        max-size: "500m"
        max-file: "6"
